apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer
  labels:
    app: customer
spec:
  replicas: 1
  template:
    metadata:
      name: customer
      labels:
        app: customer
    spec:
      containers:
        - name: customer
          image: reduxion/customer:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8085
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: kube
            - name: SPRING_DATASOURCE_USERNAME
              value: linpostgres
            - name: SPRING_DATASOURCE_USERNAME
              value: jdbc:postgresql://postgres:5432/customer # make sure to change the host from postgres to the ip from linode
            - name: SPRING_DATASOURCE_PASSWORD
              value: linpostgres #input the password value from linode
      restartPolicy: Always
  selector:
    matchLabels:
      app: customer

