server:
  port: 8085

spring:
  application:
    name: customer
  zipkin:
    base-url: http://localhost:9411/
  rabbitmq:
    addresses: "localhost:5672"

  datasource:
    url: jdbc:postgresql://localhost:5432/customer # Update with your actual database name
    username: user                                  # Your database username
    password: user                                  # Your database password
    driver-class-name: org.postgresql.Driver        # PostgreSQL driver class name

  jpa:
    hibernate:
      ddl-auto: create-drop                              # Adjust based on your requirements (e.g., create, validate)
    show-sql: true                                  # Enable SQL query logging
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true                            # Format SQL in logs for better readability

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-wih-eureka: true