server:
  port: 8086

spring:
  application:
    name: notification
  zipkin:
    base-url: http://localhost:9411/
  rabbitmq:
    host: localhost
    port: 5672
    username: guest   # Default RabbitMQ username
    password: guest   # Default RabbitMQ password
#    addresses: "rabbitmq:5672"
    connection-timeout: 15000   # Timeout in milliseconds (15 seconds)
  profiles:
    active: default #we can switch our spring profiles between default, kube and docker here
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: foo
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
#      properties:
#        spring.json.trusted.packages: "*"

  datasource:
    url: jdbc:postgresql://localhost:5432/notification # Update with your actual database name
    username: user                                  # Your database username
    password: user                                  # Your database password
    driver-class-name: org.postgresql.Driver        # PostgreSQL driver class name

  jpa:
    hibernate:
      ddl-auto: create-drop                              # Adjust based on your requirements (e.g., create, validate)
    show-sql: true                                  # Enable SQL query logging
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true                            # Format SQL in logs for better readability

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-wih-eureka: true
    enabled: true #change between true or false

rabbitmq:
  exchanges:
    internal: internal.exchange
  queues:
    notification: notification.queue
  routing-keys:
    internal-notification: internal.notification.routing-key

logging:
  level:
    org.springframework.amqp: DEBUG
    com.rabbitmq: DEBUG