apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification
  labels:
    app: notification
spec:
  replicas: 1
  template:
    metadata:
      name: notification
      labels:
        app: notification
    spec:
      containers:
        - name: notification
          image: reduxion/notification:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8085
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: kube
            - name: SPRING_DATASOURCE_USERNAME
              value: linpostgres
            - name: SPRING_DATASOURCE_USERNAME
              value: jdbc:postgresql://postgres:5432/notification # make sure to change the host from postgres to the ip from linode
            - name: SPRING_DATASOURCE_PASSWORD
              value: linpostgres #input the password value from linode
      restartPolicy: Always
  selector:
    matchLabels:
      app: notification

