spring:
#  autoconfigure:
#    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  application:
    name: eureka-server
  zipkin:
    base-url: http://zipkin:9411/
#  datasource:
#    url: jdbc:postgresql://localhost:5432/eurekaserver
#    username: user
#    password: user
#    driver-class-name: org.postgresql.Driver
#
#    jpa:
#      hibernate:
#        ddl-auto: update
#      show-sql: true
#      properties:
#        hibernate:
#          dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8761

eureka:
  client:
    fetch-registry: false
    register-with-eureka: false

#spring:
#  autoconfigure:
#    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

#management:
#  metrics:
#    enable:
#      jdbc: false
